import {upgradeFeatures} from './features';
import type {SandboxWorld,Player,Goods,Unit,Command,Pos,Bridge,Trade} from './types';
import {heightAt,land,facilities,bridgeStation,missionPlotOrigin,freePlotOrigin,freePlotSize,insidePlot,spawn,reachable,mineEntrance,mineExit,groundHeight,protectedTile,surfaceHeight} from './terrain';
import {makeBlueprint,heightsOf,compare} from './math';
import {animalRoutes,animalPose} from './animals';
import {farmKey,cropMature} from './farming';
import {connectedWork,freeValue} from './freeMission';
export const settings=()=>structuredClone((globalThis as any).NATIONLAB_CONFIG.sandbox);
function assert(ok:unknown,message:string):asserts ok {if(!ok)throw Error(message);}
export const template=(w:SandboxWorld,id:string)=>w.config.templates.find((n:any)=>n.id===id);
export const emptyGoods=(w:SandboxWorld):Goods=>Object.fromEntries(Object.keys(w.config.goods).map(g=>[g,[]]));
const orderFor=(ids:string[],index:number)=>{const rotations=[[0,1,2],[1,2,0],[2,0,1],[0,2,1],[2,1,0],[1,0,2]];return rotations[index%rotations.length].map(i=>ids[i]);};
function collection(v:any):any[]{return Array.isArray(v)?v.filter(Boolean):Object.values(v||{});}
export function normalize(raw:SandboxWorld):SandboxWorld {
 const w=structuredClone(raw);upgradeFeatures(w);w.permissions||={playerHits:false};w.config.survival||={maxHealth:20,maxHunger:20,eatHoldMs:700};w.config.freeMission||={minBlocks:10,blockCap:80,weights:{block:2,variety:24,process:8,specialty:55,allSpecialties:240}};w.config.missionMaterials||=structuredClone(settings().missionMaterials);for(const t of w.config.templates)t.technologies||=[];w.players||={};w.trades||={};w.receipts||={};w.logs=collection(w.logs);
 function goods(g:Goods|undefined):Goods{return Object.fromEntries(Object.keys(w.config.goods).map(k=>[k,collection(g?.[k])]));}
 for(const [index,n] of Object.values(w.nations).entries()){n.stock=goods(n.stock);n.nodes||={};n.voxels||={};n.freeVoxels||={};n.dug||={};n.groundHits||={};n.crops||={};n.wildlife||={};n.wildlifeHits||={};n.plan||=Array.from({length:w.config.plot.size},()=>Array(w.config.plot.size).fill(0));n.raceOrder||=orderFor(w.config.blueprints.slice(0,3).map((b:any)=>b.id),index);n.raceWorks||=[];if(n.registration)n.registration.cheers||={};if(!n.raceWorks.length&&n.registration?.status==='approved')n.raceWorks=[{...n.registration,blueprint:n.blueprint}];if(w.stage===2&&n.raceWorks.length<3)n.blueprint=n.raceOrder[n.raceWorks.length];}
 for(const p of Object.values(w.players)){p.bag=goods(p.bag);p.health??=w.config.survival.maxHealth;p.hunger??=w.config.survival.maxHunger;p.exertions??=0;p.tools||={};p.zone||='surface';p.reflections||={};p.learned||={mined:0,crafted:0,traded:0,built:0,planned:0};}
 for(const b of Object.values(w.bridges)){b.halves||={};for(const id of [b.a,b.b]){b.halves[id]||={};for(const good of Object.keys(w.config.bridge))b.halves[id][good]=collection(b.halves[id][good]);}}
 for(const t of Object.values(w.trades)){t.confirms||={};t.give||={};t.receive||={};}
 return w;
}
export function makeWorld(code:string,teacher:string,school:string,className:string,serverId:string,regionId:string,district:string,ids?:string[],now=Date.now()):SandboxWorld{
 const cfg=settings();cfg.size=Math.max(48,Math.min(96,Math.round(cfg.size)));const active=ids||cfg.activeNations;assert(active.length>=4&&active.length<=6,'나라는 4~6개를 선택해 주세요.');assert(new Set(active).size===active.length,'나라가 중복되어 있어요.');
 const w:SandboxWorld={version:3,code,teacher,school:school.trim(),className:className.trim(),serverId,regionId,district,config:cfg,permissions:{playerHits:false},nations:{},players:{},bridges:{},trades:{},stage:1,phase:'lobby',endsAt:0,remainingMs:0,lesson:0,logs:[],receipts:{},revision:0};
 active.forEach((id,index)=>{const spec=template(w,id);assert(spec,'없는 나라예요.');const n=w.nations[id]={id,stock:emptyGoods(w),nodes:{},voxels:{},plan:Array.from({length:cfg.plot.size},()=>Array(cfg.plot.size).fill(0)),blueprint:orderFor(cfg.blueprints.slice(0,3).map((b:any)=>b.id),index)[0],raceOrder:orderFor(cfg.blueprints.slice(0,3).map((b:any)=>b.id),index),raceWorks:[]};const occupied=new Set(Object.values(facilities(cfg.size)).map(p=>`${p.x},${p.z}`));const entrance=mineEntrance(cfg.size);for(let dx=-2;dx<=2;dx++)for(let dz=-1;dz<=3;dz++)occupied.add(`${entrance.x+dx},${entrance.z+dz}`);const plots=[0,1,2].map(i=>missionPlotOrigin(cfg.size,i)),free=freePlotOrigin(cfg.size,cfg.freePlot?.size||16);let serial=0;
 for(const [good,count] of Object.entries({...cfg.commonResources,...cfg.wildCrops,...spec.specialties}))for(let i=0;i<Number(count);i++){for(let tries=0;tries<10000;tries++){const seed=serial*113+i*137+tries*31+index*173;const x=4+((seed*17+7)%(cfg.size-8)),z=4+((seed*43+11+Math.floor(seed/11))%(cfg.size-12));const k=`${x},${z}`;if(!land(cfg.size,x,z)||occupied.has(k)||Math.abs(x-cfg.size/2)<3||z>cfg.size*.7||plots.some(plot=>x>=plot.x-3&&x<plot.x+cfg.plot.size+3&&z>=plot.z-3&&z<plot.z+cfg.plot.size+3)||insidePlot(x,z,free,freePlotSize(cfg.size,cfg.freePlot?.size||16)))continue;const nid=`${good}-${i}`;n.nodes[nid]={id:nid,good,x,y:heightAt(cfg.size,x,z),z,readyAt:0};occupied.add(k);break;}serial++;}
 });
 active.forEach((a,i)=>{const b=active[(i+1)%active.length],id=[a,b].sort().join('__');w.bridges[id]={id,a,b,halves:{[a]:{},[b]:{}}};});return normalize(w);
}
export function harvestCost(w:SandboxWorld,p:Player,good:string){const tool=good==='wood'?'axe':['stone','iron','copper','coalOre'].includes(good)?'pickaxe':undefined;return Math.max(1,Number(tool&&p.tools[tool as 'axe'|'pickaxe']?w.config.stamina.toolCost:w.config.stamina.harvestCost)||2);}
export function stamina(w:SandboxWorld,p:Player,now=Date.now()){return Math.min(w.config.stamina.max,p.stamina+Math.floor(Math.max(0,now-p.staminaAt)/(w.config.stamina.intervalSeconds*((p.hunger??20)<=0?4:(p.hunger??20)<=6?2:1)*1000))*w.config.stamina.refill);}
export function bridgeReady(w:SandboxWorld,b:Bridge){return [b.a,b.b].every(id=>Object.entries(w.config.bridge).every(([g,n])=>(b.halves[id]?.[g]?.length||0)>=Number(n)));}
export function bridgeProgress(w:SandboxWorld,b:Bridge){let got=0,total=0;for(const id of [b.a,b.b])for(const [g,n] of Object.entries(w.config.bridge)){total+=Number(n);got+=Math.min(Number(n),b.halves[id]?.[g]?.length||0);}return got/total;}
export function blueprint(w:SandboxWorld,nation:string){const b=w.config.blueprints.find((p:any)=>p.id===w.nations[nation].blueprint);return makeBlueprint(b.id,b.name,b.heights);}
export type MissionMaterial={good:string;source?:string};
export function missionMaterialPlan(w:SandboxWorld,nation:string):Record<string,MissionMaterial>{
 const rules=w.config.missionMaterials||settings().missionMaterials,ids=Object.keys(w.nations),chosen=rules.sources?.[nation];
 const source=chosen&&w.nations[chosen.nation]&&chosen.nation!==nation?chosen:{nation:ids[(ids.indexOf(nation)+1)%ids.length],good:''};
 source.good ||= Object.keys(template(w,source.nation)?.specialties||{})[0];
 const locals=rules.local||['wood','stone','plank','masonry'],imported=new Set((rules.importedSlots||[3,10]).map(Number)),heights=blueprint(w,nation).heights,plan:Record<string,MissionMaterial>={};let index=0;
 for(let y=0;y<w.config.plot.height;y++)for(let z=0;z<heights.length;z++)for(let x=0;x<heights[z].length;x++)if(heights[z][x]>y){plan[`${x}_${y}_${z}`]=imported.has(index)?{good:source.good,source:source.nation}:{good:locals[index%locals.length]};index++;}
 return plan;
}
export function landmarkCheck(w:SandboxWorld,nation:string){const n=w.nations[nation],v=Object.values(n.voxels),h=heightsOf(n.voxels,w.config.plot.size),match=compare(h,blueprint(w,nation)),plan=missionMaterialPlan(w,nation),keys=Object.keys(plan),materialErrors=keys.filter(key=>{const expected=plan[key],unit=n.voxels[key]?.unit;return unit&&!(unit.good===expected.good&&(!expected.source||Number(unit.sources?.[expected.source]?.[expected.good])>0));}),shapeExact=v.length===keys.length&&keys.every(key=>!!n.voxels[key]);const kinds=new Set(v.map(b=>b.unit.good)),imported=new Set(v.filter(b=>Object.keys(b.unit.sources).some(id=>id!==nation)).map(b=>b.unit.good)),processed=new Set(v.filter(b=>!w.config.goods[b.unit.good].raw).map(b=>b.unit.good));return {...match,count:v.length,kinds:kinds.size,imported:imported.size,processed:processed.size,materials:materialErrors.length===0,materialErrors,shapeExact,ready:shapeExact&&materialErrors.length===0,saving:v.length===blueprint(w,nation).min};}
export function stageReady(w:SandboxWorld){if(w.stage===1)return Object.keys(w.nations).every(id=>Object.values(w.bridges).some(b=>(b.a===id||b.b===id)&&bridgeReady(w,b)))&&Object.values(w.trades).some(t=>t.status==='accepted');if(w.stage===2)return Object.values(w.nations).every(n=>(n.raceWorks?.length||0)===3);return Object.values(w.nations).every(n=>!!n.freeEntry);}
export function freeMissionWork(w:SandboxWorld,nation:string){const area=freePlotOrigin(w.config.size,w.config.freePlot?.size||16),size=freePlotSize(w.config.size,w.config.freePlot?.size||16);return connectedWork(Object.fromEntries(Object.entries(w.nations[nation].freeVoxels||{}).filter(([,v])=>insidePlot(v.x,v.z,area,size))));}
export function totalProgress(w:SandboxWorld){const ids=Object.keys(w.nations);return ids.reduce((sum,id)=>{const n=w.nations[id];if(w.stage===1)return sum+Math.max(...Object.values(w.bridges).filter(b=>b.a===id||b.b===id).map(b=>bridgeProgress(w,b)));if(w.stage===2)return sum+((n.raceWorks?.length||0)+((n.raceWorks?.length||0)<3?Math.min(.9,Object.keys(n.voxels).length/Math.max(1,blueprint(w,id).min)*.8):0))/3;return sum+(n.freeEntry?1:Math.min(.9,Object.keys(freeMissionWork(w,id)).length/Math.max(1,w.config.freeMission.minBlocks)*.8));},0)/ids.length;}
function quantity(n:any){assert(Number.isInteger(n)&&n>0&&n<=4096,'수량은 1 이상 정수로 적어 주세요.');return Number(n);}
function exert(p:Player){p.exertions=(p.exertions??0)+1;if(p.exertions%6===0){p.hunger=Math.max(0,(p.hunger??20)-1);if(!p.hunger)p.health=Math.max(1,(p.health??20)-1);}}
function take(g:Goods,good:string,n:number){quantity(n);assert(g[good]&&g[good].length>=n,`${good} 재료가 부족해요.`);return g[good].splice(0,n);}
function put(g:Goods,units:Unit[]){for(const u of units){g[u.good]||=[];g[u.good].push(u);}}
function basket(w:SandboxWorld,b:any):Record<string,number>{assert(b&&typeof b==='object'&&!Array.isArray(b),'품목을 확인해 주세요.');const out:Record<string,number>={};for(const [g,n] of Object.entries(b)){assert(w.config.goods[g],'없는 블록이에요.');out[g]=quantity(n);}return out;}
function position(w:SandboxWorld,p:Player,positions:Record<string,Pos>){const pos=positions[p.id];return pos?.island===p.location&&(pos.zone||'surface')===(p.zone||'surface')?pos:spawn(w,p.id);}
function validNear(w:SandboxWorld,p:Player,positions:Record<string,Pos>,target:{x:number;z:number;zone?:'surface'|'mine'},island=p.location,distance=2.5){assert(reachable(position(w,p,positions),{...target,island},distance),'가까이 다가가 주세요.');}
function bridgeBetween(w:SandboxWorld,a:string,b:string){return Object.values(w.bridges).find(t=>(t.a===a&&t.b===b)||(t.a===b&&t.b===a));}
function tradeNear(w:SandboxWorld,t:Trade,positions:Record<string,Pos>){const a=w.players[t.a],b=w.players[t.b];assert(a&&b&&a.nation!==b.nation,'다른 나라 친구와 거래해요.');const bridge=bridgeBetween(w,a.nation,b.nation);assert(bridge&&bridgeReady(w,bridge),'이웃 나라와 다리 양쪽을 먼저 완성해 주세요.');for(const p of [a,b]){assert(p.zone!=='mine','지상 다리 교역소로 와 주세요.');assert(!p.dispatch,'파견 중에는 새로운 거래를 시작할 수 없어요.');assert(p.location===bridge.a||p.location===bridge.b,'거래할 두 나라의 다리로 와 주세요.');const s=bridgeStation(w,p.location,bridge.id);validNear(w,p,positions,s);}return bridge!;}
export function apply(raw:SandboxWorld,actor:string,cmd:Command,positions:Record<string,Pos>={},now=Date.now()):SandboxWorld{
 let w=normalize(raw);const id=cmd.id||`action-${w.revision+1}`;if(w.receipts[id])return w;const teacher=actor===w.teacher;let text='';const before=structuredClone(w);delete before.undo;
 for(const p of Object.values(w.players)){if(p.dispatch&&now>=p.dispatch.until){p.location=p.dispatch.home;p.zone='surface';delete p.arrival;delete p.dispatch;}const n=stamina(w,p,now);if(n!==p.stamina){p.stamina=n;p.staminaAt=now;}}
 const p=w.players[actor];const host=()=>assert(teacher,'선생님만 할 수 있어요.');const active=()=>{assert(p&&p.nation,'나라 배정을 기다려 주세요.');assert(w.phase==='playing'&&now<w.endsAt,'지금은 활동 시간이 아니에요.');};const own=()=>{active();assert(!p.dispatch&&p.location===p.nation,'자기 나라에서 할 수 있는 일이에요.');};let economic=false;
 switch(cmd.type){
 case 'join': {assert(w.phase==='lobby'||!!p,'수업이 시작했어요. 선생님께 문의해 주세요.');const nickname=String(cmd.nickname||'').trim();assert(nickname.length>0&&nickname.length<=16,'별명은 1~16자로 적어 주세요.');if(p)break;assert(Object.keys(w.players).length<w.config.maxStudents,'방 인원이 가득 찼어요.');assert(!Object.values(w.players).some(a=>a.nickname===nickname),'같은 별명이 있어요. 다른 별명을 적어 주세요.');w.players[actor]={id:actor,nickname,nation:'',location:'',bag:emptyGoods(w),stamina:w.config.stamina.max,staminaAt:now,health:w.config.survival.maxHealth,hunger:w.config.survival.maxHunger,exertions:0,tools:{},reflections:{},learned:{mined:0,crafted:0,traded:0,built:0,planned:0}};text=`${nickname} 학생이 들어왔어요.`;break;}
 case 'assign': {host();assert(w.phase==='lobby','배정은 대기실에서 해 주세요.');assert(w.players[cmd.player]&&w.nations[cmd.nation],'학생과 나라를 확인해 주세요.');w.players[cmd.player].nation=cmd.nation;w.players[cmd.player].location=cmd.nation;text='나라 배정을 바꿨어요.';break;}
 case 'autoAssign': {host();assert(w.phase==='lobby','배정은 대기실에서 해 주세요.');const ids=Object.keys(w.nations),students=Object.values(w.players).sort((a,b)=>a.id.localeCompare(b.id));assert(students.length>=ids.length,'나라 수만큼 학생이 들어와야 해요.');const counts:Record<string,number>=Object.fromEntries(ids.map(i=>[i,0]));const order=Array.isArray(cmd.order)&&cmd.order.length===students.length&&new Set(cmd.order).size===students.length&&cmd.order.every((id:string)=>w.players[id])?cmd.order.map((id:string)=>w.players[id]):students;order.forEach((student:Player,index:number)=>{const nation=index<ids.length?ids[index]:ids.reduce((a,b)=>counts[a]/template(w,a).weight<=counts[b]/template(w,b).weight?a:b);student.nation=nation;student.location=nation;counts[nation]++;});text='나라를 무작위로 배정했어요.';break;}
 case 'start': {host();assert(Object.values(w.players).length>=Object.keys(w.nations).length&&Object.values(w.players).every(p=>p.nation),'모든 학생을 나라에 배정해 주세요.');assert(w.phase!=='ended','끝난 수업이에요.');const minutes=Number(cmd.minutes||w.config.lessonMinutes);assert(minutes>=5&&minutes<=120,'활동 시간은 5~120분이에요.');w.phase='playing';w.lesson++;w.endsAt=now+minutes*60000;w.remainingMs=minutes*60000;text=`${w.lesson}차시 활동을 시작해요.`;break;}
 case 'pause': {host();assert(w.phase==='playing','진행 중인 수업이 아니에요.');w.remainingMs=Math.max(0,w.endsAt-now);w.phase='paused';text='선생님을 봐 주세요.';break;}
 case 'resume': {host();assert(w.phase==='paused'&&w.remainingMs>0,'남은 활동 시간이 없어요. 다음 차시를 시작해 주세요.');w.phase='playing';w.endsAt=now+w.remainingMs;text='활동을 이어가요.';break;}
 case 'reflection':host();w.phase='reflection';text='이번 단계에서 배운 것을 기록해요.';break;
 case 'end':host();w.phase='ended';if(w.stage===3){w.finalValues=Object.fromEntries(Object.values(w.nations).map(n=>[n.id,freeValue(w,n.freeEntry?.voxels||{})]));const submitted=Object.values(w.nations).filter(n=>n.freeEntry).map(n=>n.id),best=Math.max(...submitted.map(id=>w.finalValues![id].total));w.finalWinners=submitted.filter(id=>w.finalValues![id].total===best);}text=w.stage===3?'수업을 마쳤어요. 자유 건물 가치가 공개됐어요.':'수업을 마쳤어요.';break;
 case 'stage': {host();assert((cmd.stage===2&&w.stage===1)||(cmd.stage===3&&w.stage===2),'다음 단계만 열 수 있어요.');assert(stageReady(w),w.stage===1?'모든 나라가 다리를 하나 이상 잇고 첫 거래를 마쳐야 해요.':'모든 모둠이 세 설계도를 완성해야 해요.');w.stage=cmd.stage;w.phase='paused';w.remainingMs=w.config.lessonMinutes*60000;text=cmd.stage===2?'2단계: 세 랜드마크 스피드레이스를 시작해요.':'3단계: 자유 건축을 시작해요. 최종 가치는 수업이 끝날 때 공개돼요.';break;}
 case 'refill':host();for(const n of Object.values(w.nations))for(const node of Object.values(n.nodes))node.readyAt=0;text='자원을 보충했어요.';break;
 case 'tick':host();if(w.phase==='playing'&&now>=w.endsAt){w.phase='paused';w.remainingMs=0;}break;
 case 'enterMine': {active();assert(!p.dispatch,'파견 중에는 광산에 들어가지 않아요.');assert(p.zone==='surface','이미 지하에 있어요.');const entrance=mineEntrance(w.config.size);validNear(w,p,positions,entrance);p.zone='mine';delete p.arrival;text=`${p.nickname}: 광산 입구를 지나 지하로 내려왔어요.`;break;}
 case 'exitMine': {active();assert(p.zone==='mine','지하에서만 나갈 수 있어요.');validNear(w,p,positions,{...mineExit(w),zone:'mine'});p.zone='surface';p.arrival='mine';text=`${p.nickname}: 광산에서 지상으로 나왔어요.`;break;}
 case 'setPlayerHits': {host();w.permissions||={playerHits:false};assert(typeof cmd.enabled==='boolean','허용 여부를 확인해 주세요.');w.permissions.playerHits=cmd.enabled;text=cmd.enabled?'선생님이 학생 간 타격을 허용했어요.':'선생님이 학생 간 타격을 금지했어요.';break;}
 case 'hitPlayer': {active();assert(w.permissions?.playerHits===true,'선생님이 학생 간 타격을 금지했어요.');const other=w.players[String(cmd.target)];assert(other&&other.id!==actor,'때릴 친구를 확인해 주세요.');assert(other.location===p.location&&(other.zone||'surface')===(p.zone||'surface'),'같은 구역의 친구만 때릴 수 있어요.');validNear(w,p,positions,position(w,other,positions),p.location,3);assert(now-(p.lastPlayerHitAt||0)>=800,'잠시 뒤에 다시 시도해 주세요.');assert(p.stamina>=2,'체력이 부족해요.');p.stamina-=2;exert(p);other.stamina=Math.max(0,other.stamina-2);other.health=Math.max(1,(other.health??20)-2);other.staminaAt=now;other.lastHitAt=now;p.lastPlayerHitAt=now;text=`${p.nickname}가 ${other.nickname}을 때렸어요.`;economic=true;break;}
 case 'dig': {
  own();assert(p.zone!=='mine','지상의 땅을 골라 주세요.');
  const x=Number(cmd.x),z=Number(cmd.z);assert(Number.isInteger(x)&&Number.isInteger(z)&&!protectedTile(w,p.nation,x,z,true),'이곳은 수업 시설을 위해 보호된 땅이에요.');
  validNear(w,p,positions,{x,z,zone:'surface'},p.location,5.5);
  const nation=w.nations[p.nation],key=`${x}_${z}`,depth=nation.dug![key]||0,ground=groundHeight(w,p.nation,x,z);
  assert(depth<Math.max(1,Number(w.config.terrainDigDepth)||2)&&ground>0,'더 깊이 팔 수 없어요.');
  assert(!Object.values(nation.freeVoxels||{}).some(v=>v.x===x&&v.z===z),'위에 쌓인 블록을 먼저 치워 주세요.');
  assert(depth===0||p.tools.pickaxe,'깊은 돌층은 곡괭이가 필요해요.');assert(!nation.crops?.[key],'작물이 있는 칸은 팔 수 없어요.');const cost=harvestCost(w,p,depth===0?'dirt':'stone');assert(p.stamina>=cost,'체력이 부족해요.');
  const needed=Math.max(1,Math.min(8,Number(w.config.hitCounts?.dirt??w.config.hitCounts?.default??2)));
  if(cmd.hit===true){nation.groundHits![key]=(nation.groundHits![key]||0)+1;if(nation.groundHits![key]<needed){text=`${p.nickname}: 땅 타격 ${nation.groundHits![key]}/${needed}`;economic=true;break;}}
  delete nation.groundHits![key];nation.dug![key]=depth+1;p.stamina-=cost;exert(p);
  const good=depth===0?'dirt':'stone';p.bag[good].push({id,good,sources:{[p.nation]:{[good]:1}}});p.learned.mined++;
  text=`${p.nickname}: 땅을 한 층 파서 ${w.config.goods[good].name}을 얻었어요.`;economic=true;break;
 }
 case 'placeFree': {
  own();assert(p.zone!=='mine','지상에서 블록을 놓아 주세요.');
  const x=Number(cmd.x),z=Number(cmd.z),nation=w.nations[p.nation];
  assert(Number.isInteger(x)&&Number.isInteger(z)&&!protectedTile(w,p.nation,x,z),'이곳은 수업 시설을 위해 보호된 땅이에요.');
  validNear(w,p,positions,{x,z,zone:'surface'},p.location,5.5);
  assert(w.config.goods[cmd.good]?.placeable!==false&&w.config.goods[cmd.good],'건축할 수 있는 블록을 골라 주세요.');
  assert(Object.keys(nation.freeVoxels||{}).length<Math.max(1,Number(w.config.freeBuildLimit)||600),'이 섬의 자유 건축 블록이 가득 찼어요.');
  const y=surfaceHeight(w,p.nation,x,z),ground=groundHeight(w,p.nation,x,z),key=`${x}_${y}_${z}`;
  assert(y-ground<Math.max(1,Number(w.config.freeBuildHeight)||8),'건물을 더 높이 쌓을 수 없어요.');
  assert(!nation.freeVoxels![key],'이미 블록이 있어요.');assert(!nation.crops?.[farmKey(x,z)],'작물이 있는 칸에는 쌓을 수 없어요.');
  const unit=take(p.bag,cmd.good,1)[0];nation.freeVoxels![key]={x,y,z,unit,by:actor};if(insidePlot(x,z,freePlotOrigin(w.config.size,w.config.freePlot?.size||16),freePlotSize(w.config.size,w.config.freePlot?.size||16)))delete nation.freeEntry;p.learned.built++;
  text=`${p.nickname}: 섬에 ${w.config.goods[cmd.good].name} 블록을 놓았어요.`;economic=true;break;
 }
 case 'removeFree': {
  own();const nation=w.nations[p.nation],v=nation.freeVoxels?.[cmd.key];assert(v,'이미 없어진 블록이에요.');
  validNear(w,p,positions,{x:v.x,z:v.z,zone:'surface'},p.location,5.5);assert(!nation.freeVoxels![`${v.x}_${v.y+1}_${v.z}`],'위 블록부터 가져와 주세요.');
  put(p.bag,[v.unit]);delete nation.freeVoxels![cmd.key];if(insidePlot(v.x,v.z,freePlotOrigin(w.config.size,w.config.freePlot?.size||16),freePlotSize(w.config.size,w.config.freePlot?.size||16)))delete nation.freeEntry;text=`${p.nickname}: 자유 건축 블록을 회수했어요.`;economic=true;break;
 }
 case 'mine': {
  own();const node=w.nations[p.nation].nodes[cmd.node];
  assert(node&&node.readyAt<=now,'이미 캐낸 자원이에요. 다시 자랄 때까지 기다려 주세요.');
  validNear(w,p,positions,node,p.location,5.5);const cost=harvestCost(w,p,node.good);assert(p.stamina>=cost,'체력이 부족해요. 잠시 쉬며 거래·계획을 해 보세요.');
  const tool=w.config.goods[node.good].tool;assert(!tool||p.tools[tool as 'pickaxe'],'곡괭이를 먼저 만들어 주세요.');
  const needed=Math.max(1,Math.min(8,Number(w.config.hitCounts?.[node.good]??w.config.hitCounts?.default??1)));
  if(cmd.hit===true){node.hits=(node.hits||0)+1;if(node.hits<needed){text=`${p.nickname}: ${w.config.goods[node.good].name} 타격 ${node.hits}/${needed}`;economic=true;break;}}
  node.hits=0;p.stamina-=cost;exert(p);
  if(node.good==='wood'&&cmd.hit===true){const layers=Math.max(1,Math.min(6,Number(w.config.treeLayers)||3));node.remaining=Math.max(0,(node.remaining??layers)-1);if(!node.remaining){node.readyAt=now+w.config.resourceSeconds*1000;node.remaining=layers;}}
  else node.readyAt=now+w.config.resourceSeconds*1000;
  p.bag[node.good].push({id,good:node.good,sources:{[p.nation]:{[node.good]:1}}});p.learned.mined++;
  text=`${p.nickname}: ${w.config.goods[node.good].name} 블록 1개를 캤어요.`;economic=true;break;
 }
 case 'hunt': {
  own();assert(p.zone!=='mine','동물은 지상에서 만날 수 있어요.');
  const route=animalRoutes(w,p.nation).find(a=>a.id===cmd.animal);assert(route,'동물을 다시 찾아 주세요.');
  const n=w.nations[p.nation];assert((n.wildlife?.[route.id]||0)<=now,'동물이 다시 나타날 때까지 기다려 주세요.');
  const pose=animalPose(w,route,now);validNear(w,p,positions,{x:pose.x,z:pose.z,zone:'surface'},p.location,5.5);
  const loot=w.config.animals[p.nation]?.loot||{};if(!Object.keys(loot).length){text=`${p.nickname}: ${route.name}를 관찰했어요.`;break;}
  const cost=harvestCost(w,p,'animal');assert(p.stamina>=cost,'체력이 부족해요.');
  const needed=Math.max(1,Math.min(8,Number(w.config.hitCounts?.animal)||1));
  if(cmd.hit===true){n.wildlifeHits![route.id]=(n.wildlifeHits![route.id]||0)+1;if(n.wildlifeHits![route.id]<needed){text=`${p.nickname}: ${route.name} 타격 ${n.wildlifeHits![route.id]}/${needed}`;economic=true;break;}}
  delete n.wildlifeHits![route.id];p.stamina-=cost;exert(p);n.wildlife![route.id]=now+w.config.animalRespawnSeconds*1000;
  for(const [good,count] of Object.entries(loot))for(let i=0;i<Number(count);i++)p.bag[good].push({id:`${id}-${good}-${i}`,good,sources:{[p.nation]:{[good]:1}}});
  p.learned.mined++;text=`${p.nickname}: ${route.name}에서 ${Object.keys(loot).map(g=>w.config.goods[g].name).join('·')}을 얻었어요.`;economic=true;break;
 }
 case 'plant': {own();assert(p.zone!=='mine','밭은 지상에 있어요.');const x=Number(cmd.x),z=Number(cmd.z),good=String(cmd.good);assert(Number.isInteger(x)&&Number.isInteger(z),'밭 칸을 골라 주세요.');validNear(w,p,positions,{x,z,zone:'surface'},p.location,5.5);assert(good==='riceSeed'||good==='wheatSeed','벼 또는 밀 씨앗을 선택해 주세요.');const n=w.nations[p.nation],key=farmKey(x,z);assert(!protectedTile(w,p.nation,x,z,true)&&n.dug?.[key]&&groundHeight(w,p.nation,x,z)>=0,'땅을 한 칸 파서 밭을 먼저 만들어 주세요.');assert(!n.crops![key],'이미 작물이 자라고 있어요.');assert(!Object.values(n.freeVoxels||{}).some(v=>v.x===x&&v.z===z),'밭 위의 블록을 치워 주세요.');take(p.bag,good,1);n.crops![key]={good:good==='riceSeed'?'rice':'wheat',plantedAt:now,by:p.nickname};text=`${p.nickname}: ${w.config.goods[good].name}을 심었어요.`;economic=true;break;}
 case 'harvest': {own();assert(p.zone!=='mine','밭은 지상에 있어요.');const x=Number(cmd.x),z=Number(cmd.z);assert(Number.isInteger(x)&&Number.isInteger(z),'밭 칸을 골라 주세요.');validNear(w,p,positions,{x,z,zone:'surface'},p.location,5.5);const n=w.nations[p.nation],key=farmKey(x,z),crop=n.crops![key];assert(crop,'이 칸에는 작물이 없어요.');assert(cropMature(w,crop,now),'작물이 자라는 중이에요.');const cost=harvestCost(w,p,crop.good);assert(p.stamina>=cost,'체력이 부족해요.');p.stamina-=cost;exert(p);delete n.crops![key];const amount=Math.max(1,Math.min(4,Number(w.config.farm.harvestAmount)||2)),seed=crop.good==='rice'?'riceSeed':'wheatSeed';for(let i=0;i<amount;i++)p.bag[crop.good].push({id:`${id}-${i}`,good:crop.good,sources:{[p.nation]:{[crop.good]:1}}});p.bag[seed].push({id:`${id}-seed`,good:seed,sources:{[p.nation]:{[seed]:1}}});p.learned.mined++;text=`${p.nickname}: ${w.config.goods[crop.good].name} ${amount}개와 씨앗을 수확했어요.`;economic=true;break;}
 case 'eat': {active();const spec=w.config.goods[cmd.good];assert(spec?.food,'먹을 수 있는 음식이 아니에요.');assert(p.stamina<w.config.stamina.max||p.hunger!<w.config.survival.maxHunger||p.health!<w.config.survival.maxHealth,'배가 부르고 체력이 가득해요.');take(p.bag,cmd.good,1);p.stamina=Math.min(w.config.stamina.max,p.stamina+Number(spec.food));p.hunger=Math.min(w.config.survival.maxHunger,(p.hunger??20)+Number(spec.food)*2);p.health=Math.min(w.config.survival.maxHealth,(p.health??20)+2);p.staminaAt=now;text=`${p.nickname}: ${spec.name}을 먹고 허기와 체력을 회복했어요.`;economic=true;break;}
 case 'tool': {own();const t=w.config.tools[cmd.tool];assert(t&&!p.tools[cmd.tool as 'axe'],'도구를 확인해 주세요.');for(const [good,count]of Object.entries(t.cost))take(p.bag,good,Number(count));p.tools[cmd.tool as 'axe']=true;p.learned.crafted++;text=`${p.nickname}: ${t.name}를 만들었어요.`;economic=true;break;}
 case 'warehouse': {active();assert(p.location===p.nation||!!p.dispatch,'다른 나라 창고는 직접 가져갈 수 없어요. 다리에서 교역해 주세요.');validNear(w,p,positions,facilities(w.config.size).warehouse);const n=w.nations[p.location],q=quantity(cmd.quantity);assert(!p.dispatch||cmd.direction==='deposit','파견 중에는 받은 나라 창고의 재료를 작업대에서 사용해요.');assert(cmd.direction==='deposit'||cmd.direction==='withdraw','넣기 또는 꺼내기를 골라 주세요.');put(cmd.direction==='deposit'?n.stock:p.bag,take(cmd.direction==='deposit'?p.bag:n.stock,cmd.good,q));text=`${p.nickname}: 창고에 ${cmd.direction==='deposit'?'넣기':'꺼내기'} ${q}개`;economic=true;break;}
 case 'craft': {active();validNear(w,p,positions,facilities(w.config.size).workbench);const r=w.config.recipes[cmd.good];assert(r,'없는 조합법이에요.');assert(!r.technology||template(w,p.nation).technologies.includes(r.technology),'이 기술을 가진 나라의 학생이 필요해요.');const stock=p.dispatch?w.nations[p.location].stock:p.bag;const materials:Unit[]=[];for(const [good,count] of Object.entries(r.inputs)){if(good==='fuel'){let left=Number(count);for(const option of ['fuel',...(w.config.fuelSubstitutes||[])]){const have=Math.min(left,stock[option]?.length||0);if(have){materials.push(...take(stock,option,have));left-=have;}if(!left)break;}assert(!left,'연료·석탄·목탄이 부족해요.');}else materials.push(...take(stock,good,Number(count)));}const sources:Unit['sources']={};for(const u of materials)for(const [nation,goods]of Object.entries(u.sources)){sources[nation]||={};for(const [good,q]of Object.entries(goods))sources[nation][good]=(sources[nation][good]||0)+q/r.output;}const processes=[...new Map([...materials.flatMap(u=>u.processes||(u.processor?[{nation:u.processor,good:u.good}]:[])),{nation:p.nation,good:cmd.good}].map(v=>[v.nation+':'+v.good,v])).values()];for(let i=0;i<r.output;i++)stock[cmd.good].push({id:`${id}-${i}`,good:cmd.good,sources:structuredClone(sources),processor:p.nation,processes});p.learned.crafted++;text=`${p.nickname}: ${w.config.goods[cmd.good].name}를 가공했어요.${p.dispatch?' 받은 나라 창고에 들어갔어요.':''}`;economic=true;break;}
 case 'bridge': {own();const b=w.bridges[cmd.bridge];assert(b&&(b.a===p.nation||b.b===p.nation),'자기 쪽 다리에만 놓을 수 있어요.');validNear(w,p,positions,bridgeStation(w,p.nation,b.id));const q=quantity(cmd.quantity),need=w.config.bridge[cmd.good];assert(need&&b.halves[p.nation][cmd.good].length+q<=need,'다리에 필요한 수량을 확인해 주세요.');put(b.halves[p.nation],take(p.bag,cmd.good,q));p.learned.built+=q;text=`${p.nickname}: 다리에 ${q}개 기여했어요.${bridgeReady(w,b)?' 양쪽 다리가 이어졌어요!':''}`;economic=true;break;}
 case 'visit': {active();assert(!p.dispatch,'파견 시간이 끝나면 돌아가요.');const b=bridgeBetween(w,p.location,cmd.nation);assert(b&&bridgeReady(w,b),'다리가 이어진 이웃 섬으로 갈 수 있어요.');validNear(w,p,positions,bridgeStation(w,p.location,b.id));p.location=cmd.nation;p.zone='surface';delete p.arrival;text=`${p.nickname}: 다리를 건너 이웃 섬에 왔어요.`;break;}
 case 'return':active();assert(!p.dispatch,'파견 시간이 끝나면 자동으로 돌아가요.');p.location=p.nation;p.zone='surface';delete p.arrival;text=`${p.nickname}: 자기 섬으로 돌아왔어요.`;break;
 case 'tradeRequest': {active();assert(w.players[cmd.other]&&cmd.other!==actor,'거래할 친구를 골라 주세요.');const t:Trade={id,a:actor,b:cmd.other,give:basket(w,cmd.give||{}),receive:basket(w,cmd.receive||{}),confirms:{},status:'open',revision:0,at:now};if(cmd.dispatchSeconds){const seconds=quantity(cmd.dispatchSeconds);assert(seconds<=600&&template(w,p.nation).technologies.length,'파견은 기술을 가진 학생이 10분 이내로 할 수 있어요.');t.dispatch={from:actor,to:w.players[cmd.other].nation,seconds};}assert(Object.keys(t.give).length||Object.keys(t.receive).length||t.dispatch,'교환할 물건이나 파견을 선택해 주세요.');tradeNear(w,t,positions);assert(Object.values(w.trades).filter(t=>t.status==='open'&&(t.a===actor||t.b===actor)).length<5,'진행 중인 거래부터 마쳐 주세요.');w.trades[id]=t;text=`${p.nickname}: 교역을 요청했어요.`;break;}
 case 'tradeEdit': {active();const t=w.trades[cmd.trade];assert(t&&t.status==='open'&&(t.a===actor||t.b===actor),'진행 중인 내 거래가 아니에요.');tradeNear(w,t,positions);const b=basket(w,cmd.goods);if(t.a===actor)t.give=b;else t.receive=b;t.confirms={};t.revision++;text='제안이 바뀌어 양쪽 확인이 풀렸어요.';break;}
 case 'tradeCancel': {active();const t=w.trades[cmd.trade];assert(t&&t.status==='open'&&(t.a===actor||t.b===actor),'내 거래가 아니에요.');t.status='cancelled';text='거래 요청을 거절·취소했어요.';break;}
 case 'tradeConfirm': {active();const t=w.trades[cmd.trade];assert(t&&t.status==='open'&&(t.a===actor||t.b===actor),'진행 중인 내 거래가 아니에요.');assert(cmd.revision===t.revision,'내용이 바뀌었어요. 다시 확인해 주세요.');tradeNear(w,t,positions);t.confirms[actor]=true;if(t.confirms[t.a]&&t.confirms[t.b]){const a=w.players[t.a],b=w.players[t.b];assert(Object.keys(t.give).length||Object.keys(t.receive).length||t.dispatch,'비어 있는 거래예요.');const give=Object.entries(t.give).flatMap(([g,n])=>take(a.bag,g,n)),receive=Object.entries(t.receive).flatMap(([g,n])=>take(b.bag,g,n));put(b.bag,give);put(a.bag,receive);if(t.dispatch){const worker=w.players[t.dispatch.from];assert(!worker.dispatch,'이미 파견 중이에요.');worker.dispatch={home:worker.nation,to:t.dispatch.to,until:now+t.dispatch.seconds*1000};worker.location=t.dispatch.to;worker.zone='surface';delete worker.arrival;}t.status='accepted';a.learned.traded++;b.learned.traded++;text='양쪽이 확인하여 교역이 체결됐어요.';economic=true;}else text='거래 내용을 확인했어요. 상대 확인을 기다려요.';break;}
 case 'plan': {own();assert(w.stage===2,'공통미션 단계에서 계획판을 써요.');assert((w.nations[p.nation].raceWorks?.length||0)<3,'세 랜드마크를 모두 완성했어요.');const {x,z,height}=cmd;assert(Number.isInteger(x)&&Number.isInteger(z)&&x>=0&&z>=0&&x<w.config.plot.size&&z<w.config.plot.size&&Number.isInteger(height)&&height>=0&&height<=w.config.plot.height,'칸과 층수를 확인해 주세요.');w.nations[p.nation].plan[z][x]=height;p.learned.planned++;text=`${p.nickname}: 계획판을 고쳤어요.`;break;}
 case 'place': {own();assert(w.stage===2,'공통미션 단계에서 설계도 블록을 쌓아요.');assert((w.nations[p.nation].raceWorks?.length||0)<3,'세 랜드마크를 모두 완성했어요.');const {x,y,z}=cmd,plot=w.config.plot;assert([x,y,z].every(Number.isInteger)&&x>=0&&z>=0&&y>=0&&x<plot.size&&z<plot.size&&y<plot.height,'랜드마크 부지 안에 놓아 주세요.');const nation=w.nations[p.nation],key=`${x}_${y}_${z}`;assert(!nation.voxels[key],'이미 블록이 있어요.');assert(y===0||nation.voxels[`${x}_${y-1}_${z}`],'블록은 바닥이나 다른 블록 위에 놓아요.');const origin=missionPlotOrigin(w.config.size,nation.raceWorks?.length||0);assert(cmd.missionIndex===undefined||cmd.missionIndex===nation.raceWorks?.length,'현재 미션판에 쌓아 주세요.');validNear(w,p,positions,{x:origin.x+x,z:origin.z+z});const required=missionMaterialPlan(w,p.nation)[key];assert(required,'이 칸에는 설계도 블록이 없어요.');assert(cmd.good===required.good,`이 칸에는 ${w.config.goods[required.good]?.name||required.good} 블록이 필요해요.`);const bag=p.bag[cmd.good]||[],at=bag.findIndex(unit=>!required.source||Number(unit.sources?.[required.source]?.[required.good])>0);assert(at>=0,required.source?`${template(w,required.source).short}에서 온 ${w.config.goods[required.good].name}가 필요해요.`:'가방에 필요한 블록이 없어요.');const unit=bag.splice(at,1)[0];nation.voxels[key]={x,y,z,unit,by:actor};p.learned.built++;text=`${p.nickname}: ${w.config.goods[cmd.good].name} 블록을 쌓았어요.`;economic=true;break;}
 case 'remove': {own();assert(w.stage===2,'공통미션 단계에서 설계도 블록을 고쳐요.');const n=w.nations[p.nation];assert((n.raceWorks?.length||0)<3,'세 랜드마크를 모두 완성했어요.');const v=n.voxels[cmd.key];assert(v,'이미 없어진 블록이에요.');assert(!n.voxels[`${v.x}_${v.y+1}_${v.z}`],'위에 있는 블록부터 꺼내 주세요.');const origin=missionPlotOrigin(w.config.size,n.raceWorks?.length||0);assert(cmd.missionIndex===undefined||cmd.missionIndex===n.raceWorks?.length,'현재 미션판에서 가져와 주세요.');validNear(w,p,positions,{x:origin.x+v.x,z:origin.z+v.z});put(p.bag,[v.unit]);delete n.voxels[cmd.key];text=`${p.nickname}: 블록을 가방으로 가져왔어요.`;economic=true;break;}
 case 'register': {own();assert(w.stage===2,'스피드레이스 단계에서 등록해 주세요.');const n=w.nations[p.nation];assert((n.raceWorks?.length||0)<3,'세 랜드마크를 모두 완성했어요.');const check=landmarkCheck(w,p.nation);assert(check.ready,'설계도 모양과 각 칸의 재료·원산지를 맞춰 주세요.');const name=String(cmd.name||'').trim(),description=String(cmd.description||'').trim();assert(name.length>=1&&name.length<=40&&description.length>=5&&description.length<=400,'이름(40자 이내)과 소개(5~400자)를 적어 주세요.');const work={name,description,status:'approved' as const,by:actor,at:now,blueprint:n.blueprint,voxels:structuredClone(n.voxels),count:check.count,saving:check.saving,cheers:{}};n.raceWorks!.push(work);n.registration=work;if(n.raceWorks!.length===3){n.raceFinishedAt=now;if(!w.raceWinner){w.raceWinner=n.id;text=`${p.nickname}: 세 랜드마크 완주! ${template(w,n.id).name}이 스피드레이스 1등이에요.`;}else text=`${p.nickname}: 세 랜드마크를 완주했어요.`;}else{n.voxels={};n.plan=Array.from({length:w.config.plot.size},()=>Array(w.config.plot.size).fill(0));n.blueprint=n.raceOrder![n.raceWorks!.length];text=`${p.nickname}: ${n.raceWorks!.length}/3 완료! 다음 설계도 ${blueprint(w,n.id).name}이 열렸어요.`;}economic=true;break;}
 case 'approve': {host();throw Error('스피드레이스 작품은 조건을 맞춰 제출하면 자동 완성돼요.');}
 case 'submitFree': {own();assert(w.stage===3,'공통미션을 마친 뒤 자유 건물을 제출해요.');const name=String(cmd.name||'').trim(),description=String(cmd.description||'').trim();assert(name.length>=1&&name.length<=40&&description.length>=5&&description.length<=400,'이름(40자 이내)과 소개(5~400자)를 적어 주세요.');const n=w.nations[p.nation],voxels=freeMissionWork(w,p.nation),count=Object.keys(voxels).length;assert(count>=Math.max(1,Number(w.config.freeMission.minBlocks)||10),`서로 이어진 블록 ${w.config.freeMission.minBlocks}개 이상으로 건물을 지어 주세요.`);n.freeEntry={name,description,by:actor,at:now,voxels,count};text=`${p.nickname}: 자유 건물 ${name}을 제출했어요. 가치는 수업 끝에 공개돼요.`;economic=true;break;}
 case 'cheer': {assert(p,'참가자만 응원할 수 있어요.');const n=w.nations[cmd.nation],work=Number.isInteger(cmd.workIndex)?n?.raceWorks?.[cmd.workIndex]:n?.registration;assert(work?.status==='approved'&&w.config.cheers.includes(cmd.message),'정해진 응원 표현을 선택해 주세요.');work.cheers[actor]=cmd.message;text=`${p.nickname}: ${cmd.message}`;break;}
 case 'signal': {assert(p&&w.config.signals.includes(cmd.message),'정해진 신호를 골라 주세요.');text=`${p.nickname}: ${cmd.message}`;break;}
 case 'reflect': {assert(p,'학생만 성찰을 쓸 수 있어요.');const questions=w.config.reflections[w.stage];assert(Array.isArray(cmd.answers)&&cmd.answers.length===questions.length&&cmd.answers.every((a:any)=>typeof a==='string'&&a.trim().length>0&&a.length<=1000),'모든 문항에 짧게 답해 주세요.');p.reflections[w.stage]=cmd.answers.map((a:string)=>a.trim());text=`${p.nickname}: ${w.stage}단계 성찰을 적었어요.`;break;}
 case 'blueprint': {host();throw Error('스피드레이스 설계도 순서는 모둠마다 미리 정해져 있어요.');break;}
 case 'undo': {host();assert(w.undo,'최근 되돌릴 행동이 없어요.');const previous=w.undo.world;previous.logs=w.logs;previous.receipts=w.receipts;previous.revision=w.revision;w=previous;delete w.undo;text='선생님이 최근 행동을 되돌렸어요.';break;}
 default:throw Error('알 수 없는 행동이에요.');
 }
 if(economic)w.undo={label:text,world:before};else if(cmd.type!=='tick')delete w.undo;
 if(text)w.logs.unshift({id,actor,text,at:now});w.logs=w.logs.slice(0,120);w.revision++;w.receipts[id]={ok:true,message:'완료',at:now};for(const k of Object.keys(w.receipts).sort((a,b)=>w.receipts[a].at-w.receipts[b].at).slice(0,-250))delete w.receipts[k];return w;
}
export function csv(w:SandboxWorld){const rows=[['단계','나라','별명','문항','답변']];for(const p of Object.values(w.players))for(const [stage,answers]of Object.entries(p.reflections))answers.forEach((a,i)=>rows.push([stage,template(w,p.nation)?.name||'',p.nickname,w.config.reflections[stage][i],a]));return '\ufeff'+rows.map(r=>r.map(v=>'"'+(/^[=+\-@\t\r]/.test(v)?"'"+v:v).replace(/"/g,'""')+'"').join(',')).join('\r\n');}
