const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch({...(fs.existsSync('/usr/bin/chromium')?{executablePath:'/usr/bin/chromium'}:{}),args:['--no-sandbox','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const world=()=>page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('nl3-session'));return JSON.parse(localStorage.getItem(`nl3-room:${s.serverId}:${s.code}`)).state;});
async function position(point,zone='surface'){await page.evaluate(({point,zone})=>{const s=JSON.parse(localStorage.getItem('nl3-session')),key=`nl3-room:${s.serverId}:${s.code}`,e=JSON.parse(localStorage.getItem(key)),p=Object.values(e.state.players).find(p=>p.nation==='hualian');p.zone=zone;p.tools.pickaxe=true;e.positions[p.id]={...point,island:p.nation,zone};localStorage.setItem(key,JSON.stringify(e));},{point,zone});await page.reload();const w=await world(),idx=Object.values(w.players).findIndex(p=>p.nation==='hualian');await page.getByRole('button',{name:'학생 체험',exact:true}).nth(idx).click();await page.locator('canvas[data-renderer="webgl"]').waitFor();}
try{await page.goto(process.env.NATIONLAB_URL||'http://127.0.0.1:3003');await page.getByRole('button',{name:'설정 없이 혼자 체험하기'}).click();await page.getByRole('button',{name:'새 차시 시작',exact:true}).click();let w=await world(),x=Math.floor(w.config.size*.22),z=Math.floor(w.config.size*.24);await position({x,y:3,z:z+1});await page.keyboard.down('w');await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.zone==='mine');await page.keyboard.up('w');await page.screenshot({path:'/workspace/onboarding/nationlab-underground.png'});w=await world();assert.equal(Object.values(w.players).find(p=>p.nation==='hualian').zone,'mine');
const n=Object.values(w.nations.hualian.nodes).find(n=>n.good==='iron');assert.equal(n.zone,'mine');await position({x:n.x,y:n.y,z:n.z+2},'mine');const c=await page.locator('canvas').boundingBox();await page.mouse.move(c.x+c.width*.7,c.y+c.height*.4);await page.mouse.down();await page.mouse.move(c.x+c.width*.7,c.y+c.height*.4+65,{steps:8});await page.mouse.up();await page.waitForFunction(()=>JSON.parse(document.querySelector('canvas').dataset.aim||'null')?.kind==='resource');await page.getByRole('button',{name:'동작',exact:true}).click();await page.waitForFunction(()=>{const s=JSON.parse(localStorage.getItem('nl3-session')),e=JSON.parse(localStorage.getItem(`nl3-room:${s.serverId}:${s.code}`));return Object.values(e.state.players).find(p=>p.nation==='hualian').bag.iron.length===1;});
await page.reload();const idx=Object.values((await world()).players).findIndex(p=>p.nation==='hualian');await page.getByRole('button',{name:'학생 체험',exact:true}).nth(idx).click();await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.zone==='mine');
w=await world();const exit={x:Math.floor(w.config.size/2),y:w.config.mine.floor,z:w.config.size-w.config.mine.margin-2};await position(exit,'mine');await page.keyboard.down('s');await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.zone==='surface');await page.keyboard.up('s');w=await world();assert.equal(Object.values(w.players).find(p=>p.nation==='hualian').zone,'surface');assert.equal(Object.values(w.players).find(p=>p.nation==='hualian').bag.iron.length,1);assert.deepEqual(errors,[]);console.log('PASS walking through mine entrance/exit, underground raycast mining, inventory retention and underground refresh');
}catch(e){await page.screenshot({path:'/workspace/onboarding/mine-browser-failure.png'});console.error(await page.locator('body').innerText());throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
