const {chromium}=require('playwright');const assert=require('node:assert/strict');
const base=process.env.NATIONLAB_URL||'http://127.0.0.1:3003';
(async()=>{const browser=await chromium.launch({...(require('node:fs').existsSync('/usr/bin/chromium')?{executablePath:'/usr/bin/chromium'}:{}),headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const errors=[];
async function page(){const c=await browser.newContext({viewport:{width:1280,height:800}}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.route('**/config.js*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+`\nglobalThis.NATIONLAB_CONFIG.firebase={apiKey:'fake-key',authDomain:'demo-nationlab.firebaseapp.com',databaseURL:'https://demo-nationlab.firebaseio.com',projectId:'demo-nationlab',appId:'fake-app'};globalThis.NATIONLAB_CONFIG.emulator={enabled:true,host:'127.0.0.1',authPort:9099,databasePort:9000,firestorePort:8080};`});});await p.goto(base);return p;}
const teacher=await page();try{
// Auth emulator accepts an unsigned test IdP token. No production login bypass exists.
await teacher.evaluate(async()=>{const a=await import('/node_modules/.vite/deps/firebase_app.js'),f=await import('/node_modules/.vite/deps/firebase_auth.js');const app=a.initializeApp(globalThis.NATIONLAB_CONFIG.firebase,'sandbox-demo-nationlab');const auth=f.getAuth(app);f.connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});const enc=o=>btoa(JSON.stringify(o)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');const token=enc({alg:'none',typ:'JWT'})+'.'+enc({iss:'https://accounts.google.com',aud:'fake-key',sub:'teacher-'+Date.now(),email:'teacher@example.test',email_verified:true,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600})+'.';await f.signInWithCredential(auth,f.GoogleAuthProvider.credential(token));});
await teacher.getByRole('button',{name:'선생님',exact:true}).click();await teacher.getByLabel('학교 이름').fill('실시간 검증 학교');await teacher.getByRole('button',{name:'우리 반 세계 만들기'}).click();await teacher.locator('.sb-code').waitFor();const code=(await teacher.locator('.sb-code').innerText()).trim();
const students=[];for(let i=0;i<5;i++){const s=await page();await s.getByLabel('방 코드').fill(code);await s.getByLabel('별명').fill('학생'+i);await s.getByRole('button',{name:'섬으로 들어가기'}).click();await s.getByRole('heading',{name:'우리 나라를 기다려요'}).waitFor();students.push(s);}
await teacher.getByRole('button',{name:'나라 자동 배정'}).click();await teacher.getByRole('button',{name:'새 차시 시작'}).click();await students[0].locator('.sb-hud-top').waitFor();
async function state(p){return p.evaluate(async()=>{const apps=await import('/node_modules/.vite/deps/firebase_app.js'),db=await import('/node_modules/.vite/deps/firebase_database.js');const s=JSON.parse(localStorage.getItem('nl3-session'));return (await db.get(db.ref(db.getDatabase(apps.getApp('sandbox-demo-nationlab')),`sandboxes/${s.serverId}/${s.code}/state`))).val();});}
const world=await state(teacher),uid=[];for(const s of students)uid.push(await s.evaluate(()=>JSON.parse(localStorage.getItem('nl3-session')).uid));const pair=uid.filter(id=>world.players[id].nation==='hualian');assert.equal(pair.length,2);const p0=students[uid.indexOf(pair[0])],p1=students[uid.indexOf(pair[1])],node=Object.values(world.nations.hualian.nodes).find(n=>n.good==='wood');
for(const p of [p0,p1])await p.evaluate(async node=>{const api=await import('/src/sandbox/service.ts');const s=api.restore(),db=await import('/node_modules/.vite/deps/firebase_database.js'),apps=await import('/node_modules/.vite/deps/firebase_app.js');const w=(await db.get(db.ref(db.getDatabase(apps.getApp('sandbox-demo-nationlab')),`sandboxes/${s.serverId}/${s.code}/state`))).val();const terrain=await import('/src/sandbox/terrain.ts');const pos=[{x:node.x+1,z:node.z},{x:node.x-1,z:node.z},{x:node.x,z:node.z+1},{x:node.x,z:node.z-1}].find(v=>terrain.walkable(w,'hualian',v.x,v.z));await api.move(s,w,{...pos,island:'hualian',y:1});},node);
await teacher.waitForTimeout(250);const started=Date.now();const race=await Promise.all([p0,p1].map(p=>p.evaluate(async node=>{const api=await import('/src/sandbox/service.ts');try{await api.send(api.restore(),{type:'mine',node:node.id});return 'success';}catch(e){return e.message;}},node)));assert.equal(race.filter(x=>x==='success').length,1);const after=await state(p1);assert.equal(after.players[pair[0]].bag?.wood?.length||after.players[pair[1]].bag?.wood?.length,1);assert.ok(after.nations.hualian.nodes[node.id].readyAt>Date.now());console.log('5 student contexts + Google teacher: shared mining race passed;',Date.now()-started,'ms including both receipts');
const savedUid=await p0.evaluate(()=>JSON.parse(localStorage.getItem('nl3-session')).uid);await p0.reload();await p0.locator('.sb-hud-top').waitFor();assert.equal(await p0.evaluate(()=>JSON.parse(localStorage.getItem('nl3-session')).uid),savedUid);
await teacher.getByRole('button',{name:'모두 멈춤',exact:true}).click();await p0.getByRole('heading',{name:'잠깐 멈춤',exact:true}).waitFor();await teacher.screenshot({path:'/workspace/onboarding/nationlab-sandbox-teacher.png',fullPage:true});
await teacher.evaluate(async()=>{const api=await import('/src/sandbox/service.ts');await api.removeRoom(api.restore());});assert.deepEqual(errors,[]);console.log('refresh identity, teacher pause and room/Firestore deletion passed');
}catch(e){console.error('Teacher screen:',await teacher.locator('body').innerText());await teacher.screenshot({path:'/workspace/onboarding/sandbox-live-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
