const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const {execFileSync}=require('node:child_process');
(async()=>{const browser=await chromium.launch({...(require('node:fs').existsSync('/usr/bin/chromium')?{executablePath:'/usr/bin/chromium'}:{}),args:['--no-sandbox','--enable-unsafe-swiftshader']});const p=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.NATIONLAB_URL||'http://127.0.0.1:3003';
const read=()=>p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('nl3-session'));return JSON.parse(localStorage.getItem(`nl3-room:${s.serverId}:${s.code}`));});
const pick=async()=>{await p.getByRole('button',{name:'학생 체험',exact:true}).first().click();await p.locator('canvas[data-renderer="webgl"]').waitFor();};
try{await p.goto(base);await p.screenshot({path:'/workspace/onboarding/nationlab-sandbox-entry.png',fullPage:true});await p.getByRole('button',{name:'선생님',exact:true}).click();await p.getByText('처음 한 번 · Firebase 웹 설정',{exact:true}).click();await p.screenshot({path:'/workspace/onboarding/nationlab-sandbox-settings.png',fullPage:true});await p.getByRole('button',{name:'설정 없이 혼자 체험하기'}).click();await p.getByRole('button',{name:'새 차시 시작'}).click();await pick();let e=await read(),id=Object.keys(e.state.players)[0];let z=e.positions[id].z;await p.keyboard.down('w');await p.waitForTimeout(450);await p.keyboard.up('w');e=await read();assert.ok(e.positions[id].z<z);assert.notEqual(e.positions[id].z%1,0);assert.equal(await p.locator('.sb-hotbar button').count(),9);assert.equal(await p.locator('.sb-game [role="tab"]').count(),0);assert.ok(await p.evaluate(()=>!!document.fullscreenElement));
// Deliberate fixture: put the player near a tree and supply the starter tool cost.
await p.evaluate(id=>{const s=JSON.parse(localStorage.getItem('nl3-session')),key=`nl3-room:${s.serverId}:${s.code}`,e=JSON.parse(localStorage.getItem(key)),w=e.state,a=w.players[id];const n=Object.values(w.nations[a.nation].nodes).find(n=>n.good==='wood'&&n.y===1);e.positions[id]={island:a.nation,x:n.x,y:n.y,z:n.z+2};for(const [good,n]of Object.entries({wood:3,stone:5}))for(let i=0;i<n;i++)a.bag[good].push({id:`fixture-${good}-${i}`,good,sources:{[a.nation]:{[good]:1}}});localStorage.setItem(key,JSON.stringify(e));},id);await p.reload();await pick();await p.waitForFunction(()=>JSON.parse(document.querySelector('canvas').dataset.aim||'null')?.kind==='resource');await p.getByRole('button',{name:'캐기',exact:true}).click();await p.waitForFunction(()=>{const s=JSON.parse(localStorage.getItem('nl3-session')),e=JSON.parse(localStorage.getItem(`nl3-room:${s.serverId}:${s.code}`));return Object.values(e.state.players)[0].learned.mined===1;});await p.getByRole('button',{name:'내 가방 열기'}).click();await p.getByRole('button',{name:'곡괭이 만들기',exact:true}).click();await p.getByRole('button',{name:'활동 창 닫기'}).click();await p.waitForFunction(()=>document.querySelector('canvas')?.dataset.tool==='pickaxe');await p.screenshot({path:'/workspace/onboarding/nationlab-sandbox-student.png'});
// Fixture is produced by real engine mining, bridge/trade/placement/approval commands.
const world=JSON.parse(execFileSync('./node_modules/.bin/tsx',['-e',"import {simulateSandbox} from './scripts/sandbox-simulate';console.log(JSON.stringify(simulateSandbox(true).world))"],{encoding:'utf8'}));
await p.evaluate(w=>{const s=JSON.parse(localStorage.getItem('nl3-session')),key=`nl3-room:${s.serverId}:${s.code}`,e=JSON.parse(localStorage.getItem(key));w.teacher=s.uid;w.code=s.code;w.serverId=s.serverId;w.endsAt=Date.now()+2400000;e.state=w;e.positions={};localStorage.setItem(key,JSON.stringify(e));},world);await p.reload();await pick();await p.getByRole('button',{name:'게임 설정'}).click();await p.getByRole('button',{name:'우리 반 작품 감상',exact:true}).click();assert.equal(await p.locator('.sb-work').count(),4);assert.equal(await p.locator('.sb-work canvas').count(),0);await p.getByLabel('블록 개수 예상',{exact:true}).first().fill('15');await p.getByRole('button',{name:'예상하고 입체 보기',exact:true}).first().click();await p.locator('.sb-work canvas').first().waitFor();await p.getByLabel('원산지 색으로 보기').check();await p.screenshot({path:'/workspace/onboarding/nationlab-sandbox-gallery.png'});await p.getByRole('button',{name:'멋져요',exact:true}).click();await p.getByRole('button',{name:'활동 창 닫기'}).click();await p.getByRole('button',{name:'게임 설정'}).click();await p.getByRole('button',{name:'배움 기록',exact:true}).click();await p.locator('.sb-modal textarea').nth(0).fill('다른 나라에서 온 모래와 목화를 썼어요.');await p.locator('.sb-modal textarea').nth(1).fill('우리의 나무와 바꾸어 서로 필요한 것을 얻었어요.');await p.getByRole('button',{name:'성찰 제출'}).click();await p.getByText('내 답이 저장됐어요.',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('PASS full-screen HUD, movement, actual mining, tool crafting, engine-produced gallery, guess-before-3D, origin toggle, cheers and reflection');
}catch(e){await p.screenshot({path:'/workspace/onboarding/sandbox-browser-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
